#!/bin/sh

echo "POSTing two new questions:"
curl -v -X POST localhost:3000/questions -d "title=Test Question from CURL" -d "content=Question question 123" -H "Accept: application/json"
echo ""
curl -v -X POST localhost:3000/questions -d "title=Lorem ipsum dolor sit" -d "content=Question question 123" -H "Accept: application/json"
echo ""
echo "Trying to PUT to question 1"
curl -v -X PUT localhost:3000/questions/1 -d "title=Edited by CURL!" -d "content=Edited edited 123" -H "Accept: application/json"
echo ""
echo "Trying to PUT to question 65536"
curl -v -X PUT localhost:3000/questions/65536 -d "title=Edited by CURL!" -d "content=Edited edited 123" -H "Accept: application/json"
echo ""
echo "DELETE question 2"
curl -v -X DELETE localhost:3000/questions/2 -H "Accept: application/json"
echo ""
echo "Try to DELETE question 2 again!"
curl -v -X DELETE localhost:3000/questions/2 -H "Accept: application/json"
echo ""
echo "GET question 1 as JSON"
curl -v -X GET localhost:3000/questions/1 -H "Accept: application/json"
echo ""
echo "GET question 1 as HTML"
curl -v -X GET localhost:3000/questions/1 -H "Accept: text/html"
echo ""
echo "GET question 1 as unsupported format"
curl -v -X GET localhost:3000/questions/1 -H "Accept: weird/format"
echo ""
echo "GET all questions as JSON"
curl -v -X GET localhost:3000/questions -H "Accept: application/json"
echo ""
echo "POST a comment and answer to question 1"
curl -v -X POST localhost:3000/questions/1/answers -d "title=Test Answer" -d "content=123123123" -H "Accept: application/json"
echo ""
curl -v -X POST localhost:3000/questions/1/comments -d "title=Test Comment" -d "content=123" -H "Accept: application/json"
echo ""
echo "GET all comments on question 1"
curl -v -X GET localhost:3000/questions/1/comments -H "Accept: application/json"
echo ""
